spring.application.name=beyazesya

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BeyazEsyaDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=beyazesya_user
spring.datasource.password=beyaz123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

spring.jpa.open-in-view=false
